language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy3.5"
cache: pip
install:
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install .

script:
- py.test --cov=bmw_ibus/
after_success:
- coveralls