language: python
python:
  - "2.7"
  - "3.6"
  - "pypy3.5"
cache: pip
install:
- pip install pytest
- pip install pytest-cov
- pip install -r requirements.txt
# command to run tests
script:
- py.test --cov=bmw-ibus/
after_success:
- coveralls